### ISSUE TITLE
Use Pipeline Caching in the build

### ISSUE THREAD

**Issue by johnterickson** [johnterickson/cargo2junit#14]
I'm trying to use my little tool as a testbed for using Pipeline Caching for building Rust projects.  I hope to standardize a recommendation.

 My general approach is:

* Cache is per config (e.g. x86_64-pc-windows-msvc+vs2017-win2016)
* Cache contains cargo+rustc toolchain 
* Cache contains sccache local folder
* Cache contains other "cargo install"ed tools that the build itself uses (e.g. cargo2junit)
* Cache contains tools to make caching work (sccache and cargo-cache)
* Cache contains mechanism to update tools (cargo-update)

Some questions?
- [ ] Is sccache ready for general recommendation? Any gotchas?
- [ ] Will new versions of sccache/cargo-cache handle a cache folder from an older version well?
- [ ] What are the right parameters for cargo-cache so the cache doesn't grow indefinitely?
- [ ] Will perf be better even though we're doing all this? 😁

Here's an example build - just look at VS2019-tar and OSX-tar:
https://dev.azure.com/codesharing-su0/cachesandbox/_build/results?buildId=15929&view=results
and it's YAML:
https://github.com/johnterickson/cargo2junit/blob/cacheTar/azure-pipelines.yml

**Comment by pietroalbini** [comment]
I'll let kinnison reply more in-depth here, but just a thought:

> Cache contains cargo+rustc toolchain

Make sure you don't cache the docs otherwise you're going to kill Windows performance.

**Comment by alexcrichton** [comment]
>  Is sccache ready for general recommendation? Any gotchas?

I don't think `sccache` is at a point where it's ready to be turned on by default, but it would be nice if it were a one-step config to turn it on by default. It's not an officially supported tool so it breaks from time to time and needs updates, and additionally it only tends to have a modest impact on caching performance and so it's not necessarily a killer thing to add.

>  Will new versions of sccache/cargo-cache handle a cache folder from an older version well?

One note I'd add is that Cargo has an unstable feature, `-Z install-upgrade`, which makes `cargo install foo` skip installation if `foo` is cached at the most recent version. In that sense caching Cargo-installed binaries will eventually be cached and never rebuilt so long as `foo` doesn't change in version. Having `cargo-update` in the meantime seems reasonable though!

In general though Cargo should always handle old caches pretty well, and it's a bug if it doesn't!

>  What are the right parameters for cargo-cache so the cache doesn't grow indefinitely?

I'm not personally that familiar with `cargo-cache` as a tool, so I'm not entirely sure. I suspect that caching `$HOME/.cargo` would be pretty safe though since that would contain git dependencies, crates.io indexes and downloaded sources, etc. It tends to be pretty small for single-project builds, but unfortunately we don't have a great ways to automatically prune it over time right now :(

Helping manage this is something we'd like to add to Cargo though!

> Will perf be better even though we're doing all this? 

I imagine that caching Cargo's registry index is probably one of the clearest "definitely a win" things that you could do. We always download the whole registry anyway, so having it pre-cached means we just happen to download less. Beyond that caching does indeed run a risk of schlepping too many bytes around that don't end up getting used. That's where I think that having this be easily-opt-in for projects to experiment with may be best rather than having it on-by-default.

**Comment by kinnison** [comment]
Things worth noting from cache research I did with Travis a few months ago.

1. The cache of `target/` should also be keyed on the compiler version, or perhaps simply made to be PR specific rather than cached for the project as a whole
2. The contents of `.cargo/` are worth caching, but it's worth *NOT* caching `.cargo/registry/src` since that can be rebuilt from the `.crate` files in `.cargo/registry/cache` and lots of files take longer to recompress
3. It's worth noting that if you cache `.cargo/` *and* `.rustup/` then a default mechanism of running the normal `rustup-init` process will *NOT* update your toolchains, you'll want something like 1. run your rustup-init and then 2. run `rustup update`

From experimentation with rustup.

`sccache` is still a very loose benefit.  It *can* result in compile speed gains, but since the cache is sensitive to so much, you end up keying it on PRs at which point, frankly, the `target/` cache is sufficient.  I'm not sure we're keeping sccache going forward.

Indeed from my own experimentation, unless you keep sccache very up-to-date then it keeps failing as we add newer options to rustc and the like.

I'm afraid I don't have any input on extra tool installation since rustup doesn't install any others, but in general, caching the toolchain is worthwhile as it caching the cargo index and downloaded crates can help too.

One point made above about caching the docs -- We're very close now to supporting minimal rust toolchain installation in rustup, which will mean being able to avoid installing the docs at all.  It's probably not worth adding code to try and avoid the docs since if rustup thinks they're installed, it'll get very upset when you try and run `rustup update` or similar if the files aren't properly present.
