### ISSUE TITLE
There already is a cargo2junit...

### ISSUE THREAD

**Issue by johnterickson** [johnterickson/cargo2junit#4]
Hadn't seen it on crates.io, but just found https://github.com/mgr-inz-rafal/cargo2junit while searching for my own project. 🤦‍♂️

**Comment by johnterickson** [comment]
Hi @mgr-inz-rafal, didn't mean to name collide!

**Comment by mgr-inz-rafal** [comment]
Hello,
No worries :)

What I am more surprised of is why cargo still cannot generate JUnit compatible output itself... Seems like there is a need for that.

I think that would be the most appropriate solution, that's why I don't actively develop my version of the converter as long as it just serves me well on Jenkins ;)

**Comment by jerickmsft** [comment]
Agreed on needing a CI-compatible output!  I'm trying to get clarity on it in #wg-testing https://discordapp.com/channels/442252698964721669/459150014518788107

**Comment by johnterickson** [comment]
@mgr-inz-rafal Feel free to +1 https://github.com/rust-lang/rust/issues/51924.

Does Jenkins support formats other than JUnit?  I don't see "Ignored" in the JUnit spec... https://www.ibm.com/support/knowledgecenter/en/SSUFAU_1.0.0/com.ibm.rsar.analysis.codereview.cobol.doc/topics/cac_useresults_junit.html

**Comment by mgr-inz-rafal** [comment]
There are tons of plugins available for Jenkins, but at the time I needed to integrate it with Rust project I didn't manage to find any that could parse Cargo output. Maybe things have changed...
